<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation[] $data
 * @var string $type
 * @var array $options
 */

$translate = $this->plugin('translate');

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

if (empty($options['title'])):
    $title = [
        'tree' => $translate('Tree'),
        'branch' => $translate('Branch'),
        'custom' => $translate('Tree'),
    ];
    $title = $title[$type];
else:
    $title = $options['title'];
endif;

?>
<div class="ead ead-tree">
    <h4><?= $title ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No component.') ?>
    </p>
    <?php else: ?>
        <?= $this->partial('common/ead-tree-recursive', ['data' => $data, 'options' => $options]) ?>
    <?php endif; ?>
</div>
