<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 * @var \Omeka\Api\Representation\ItemRepresentation[] $data
 * @var string $type
 * @var array $options
 */

$translate = $this->plugin('translate');

if (empty($data) && !empty($options['hideIfEmpty'])):
    return;
endif;

if (isset($options['title'])):
    $title = $options['title'];
else:
    $title = [
        'narrowers' => $translate('Sub-components'),
        'relateds' => $translate('Related components'),
        'siblings' => $translate('Sibling components'),
        // The title is the same than siblings.
        'siblingsOrSelf' => $translate('Sibling components'),
        'ascendants' => $translate('Ascendant components'),
        'descendants' => $translate('Descendant components'),
        'custom' => $translate('Linked components'),
    ];
    $title = $title[$type];
endif;

$itemId = $item ? $item->id() : null;
?>

<div class="ead ead-list <?= $options['class'] ?>">
    <h4><?= $title ?></h4>
    <?php if (empty($data)): ?>
    <p>
        <?= $translate('No component.') ?>
    </p>
    <?php else: ?>
    <ul>
        <?php foreach ($data as $concept): ?>
        <?php $isItem = $concept->id() === $itemId; ?>
        <li<?php if ($isItem) echo ' class="active"'; ?>><?= $concept->link($concept->displayTitle()) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
