<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImportEad\Form\ImportForm $form
 */

$translate = $this->plugin('translate');
$form->prepare();
?>

<?php echo $this->pageTitle($translate('Import EAD')); ?>
<h3><?php echo $translate('Import'); ?></h3>
<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <input type='submit' value="<?= $translate('Submit') ?>" aria-label="<?= $translate('Submit') ?>"/>
</fieldset>
<p class="explanation">
    <?php echo $translate('Import an EAD repository as Omeka items.'); ?>
    <?php echo $translate('Upload a xml file or set the url of the EAD end point.'); ?>
</p>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag($form); ?>
